version: '3.7'
volumes:
  bundle_cache:
  pgdata:
services:
  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    build: .
    volumes:
      - bundle_cache:/bundle
      - .:/app
      - ./log/puma:/var/log/pluto/puma
      - ./log/pluto:/opt/pluto/log
    ports:
      - "3001:3000"
    depends_on:
      - db
